<<echo=FALSE, cache=FALSE>>=
set_parent('r4p.main.Rnw')
opts_knit$set(concordance=TRUE)
@

\chapter{Simulation}\label{chap:simulation}

%\begin{abstract}
%  In this chapter we explain how to use one spectral simulation model and analyse the resulting data.
%\end{abstract}

%%%%
\section{Task: Calling TUV in batch mode}\label{sec:}

\section{Task: Importing into R simulated spectral data from TUV}\label{sec:}
