\chapter{Weighted and effective irradiance}

\begin{abstract}
  In this chapter we explain how to calculate weighted energy and photon irradiances from spectral irradiance.
\end{abstract}

\section{Packages used in this chapter}

For executing the examples listed in this chapter you need first to load the following packages from the library:
<<>>=
library(photobiology)
library(photobiologyVIS)
library(photobiologyUV)
@

%%%%
\section{Introduction}\label{sec:wt:intro}
